#!/bin/bash

# Where is the Gitolite lib dir?
GL_LIBDIR=/some/where/gitolite/src/lib
# Test repetition.
INTERVAL=2
export GL_LIBDIR

while [ : ]
do
    clear
    prove --color -v
    sleep ${INTERVAL}
done
