#!/bin/bash

# CHANGE THIS to where the Gitolite lib dir is:
GL_LIBDIR=/some/where/gitolite/src/lib
export GL_LIBDIR
# Test repetition.
INTERVAL=1

# I use loop instead of watch because watch does not support colors.
while [ : ]
do
    clear
    prove --color -v -l
    sleep ${INTERVAL}
done
